### HOME ###

/:
  controller: MainController
  action: home

/login:
  controller: MainController
  action: login

/logout:
  controller: MainController
  action: logout

### USER ###

/users:
  controller: CwUserController
  action: index

/user/new:
  controller: CwUserController
  action: new

/user/edit:
  controller: CwUserController
  action: edit

/user/edit/role:
  controller: CwUserController
  action: editRole
### PLAYER ###

/players:
  controller: PlayersController
  action: index

/player/edit:
  controller: PlayersController
  action: edit

/player/edit/name:
  controller: PlayersController
  action: editName

/player/edit/license:
  controller: PlayersController
  action: editLicense

/player/edit/cash:
  controller: PlayersController
  action: editCash

/player/edit/bankacc:
  controller: PlayersController
  action: editBankacc

/player/delete/vehicle:
  controller: PlayersController
  action: deleteVehicle

/player/delete/house:
  controller: PlayersController
  action: deleteHouse

/player/delete/container:
  controller: PlayersController
  action: deleteContainer

/player/edit/coplevel:
  controller: PlayersController
  action: editCopLevel

/player/edit/mediclevel:
  controller: PlayersController
  action: editMedicLevel
### VEHICLES ###

/vehicles:
  controller: VehiclesController
  action: index

/vehicle/edit:
  controller: VehiclesController
  action: edit